// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/new": {
    params: {};
  };
  "/admin/:id": {
    params: {
      "id": string;
    };
  };
  "/forms/:id": {
    params: {
      "id": string;
    };
  };
  "/api/forms": {
    params: {};
  };
  "/api/forms/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/register" | "/auth/login" | "/auth/logout" | "/admin" | "/admin/new" | "/admin/:id" | "/forms/:id" | "/api/forms" | "/api/forms/:id";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/admin.new.tsx": {
    id: "routes/admin.new";
    page: "/admin/new";
  };
  "routes/admin.$id.tsx": {
    id: "routes/admin.$id";
    page: "/admin/:id";
  };
  "routes/forms.$id.tsx": {
    id: "routes/forms.$id";
    page: "/forms/:id";
  };
  "routes/api.forms.ts": {
    id: "routes/api.forms";
    page: "/api/forms";
  };
  "routes/api.forms.$id.ts": {
    id: "routes/api.forms.$id";
    page: "/api/forms/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin.new": typeof import("./app/routes/admin.new.tsx");
  "routes/admin.$id": typeof import("./app/routes/admin.$id.tsx");
  "routes/forms.$id": typeof import("./app/routes/forms.$id.tsx");
  "routes/api.forms": typeof import("./app/routes/api.forms.ts");
  "routes/api.forms.$id": typeof import("./app/routes/api.forms.$id.ts");
};